# Generated by Django 3.1.1 on 2021-03-11 08:34

from django.db import migrations, models
import server.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=32, unique=True)),
                ('passwd', models.CharField(max_length=256)),
                ('isAdmin', models.BooleanField(default=False)),
                ('registerDate', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('birthday', models.DateTimeField(null=True)),
                ('education', models.IntegerField(null=True)),
                ('wechart', models.CharField(max_length=64, null=True)),
                ('qq', models.CharField(max_length=64, null=True)),
                ('email', models.CharField(max_length=64, null=True)),
                ('telephone', models.CharField(max_length=16, null=True)),
                ('status', server.models.JSONFieldUtf8(null=True)),
            ],
        ),
    ]
