# Generated by Django 3.1.1 on 2021-01-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('u_uname', models.CharField(max_length=32, unique=True)),
                ('u_passwd', models.CharField(max_length=128)),
                ('u_is_admin', models.BooleanField(default=False)),
                ('u_register_date', models.DateTimeField()),
                ('u_name', models.CharField(blank=True, max_length=32)),
                ('u_gender', models.BooleanField(default=False)),
                ('u_birthday', models.DateTimeField(blank=True)),
                ('u_education', models.IntegerField(blank=True)),
                ('u_wechart', models.CharField(blank=True, max_length=64)),
                ('u_qq', models.CharField(blank=True, max_length=64)),
                ('u_email', models.CharField(blank=True, max_length=64)),
                ('u_telephone', models.CharField(blank=True, max_length=16)),
                ('u_status', models.JSONField()),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
