# Generated by Django 3.1.1 on 2021-03-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='gender',
            field=models.BooleanField(null=True),
        ),
    ]
