# Generated by Django 3.1.1 on 2021-02-02 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_u_is_authenticated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='u_is_authenticated',
        ),
    ]
