# Generated by Django 3.1.1 on 2021-01-14 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distinguish',
            fields=[
                ('d_id', models.AutoField(primary_key=True, serialize=False)),
                ('d_words', models.JSONField()),
                ('d_content', models.TextField()),
            ],
            options={
                'db_table': 'Distinguish',
            },
        ),
        migrations.CreateModel(
            name='Etyma',
            fields=[
                ('e_name', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('e_meaning', models.TextField(blank=True, max_length=512)),
                ('e_type', models.IntegerField()),
            ],
            options={
                'db_table': 'Etyma',
            },
        ),
        migrations.CreateModel(
            name='Grammar',
            fields=[
                ('g_id', models.AutoField(primary_key=True, serialize=False)),
                ('g_type', models.JSONField()),
                ('g_tags', models.JSONField()),
                ('g_content', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'Grammar',
            },
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('s_en', models.CharField(max_length=512)),
                ('s_ch', models.CharField(max_length=512)),
                ('s_word', models.JSONField()),
                ('s_type', models.IntegerField(default=0)),
                ('s_tags', models.JSONField()),
                ('s_tense', models.JSONField()),
                ('s_form', models.JSONField()),
                ('s_synonym', models.JSONField()),
                ('s_antonym', models.JSONField()),
                ('s_grammar_id', models.JSONField()),
            ],
            options={
                'db_table': 'Sentence',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('u_uname', models.CharField(max_length=32, unique=True)),
                ('u_passwd', models.CharField(max_length=128)),
                ('u_is_admin', models.BooleanField(default=False)),
                ('u_register_date', models.DateTimeField()),
                ('u_name', models.CharField(blank=True, max_length=32)),
                ('u_gender', models.BooleanField(default=False)),
                ('u_birthday', models.DateTimeField(blank=True)),
                ('u_education', models.IntegerField(blank=True)),
                ('u_wechart', models.CharField(blank=True, max_length=64)),
                ('u_qq', models.CharField(blank=True, max_length=64)),
                ('u_email', models.CharField(blank=True, max_length=64)),
                ('u_telephone', models.CharField(blank=True, max_length=16)),
                ('u_status', models.JSONField()),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('w_name', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('w_voice_us', models.CharField(blank=True, max_length=32)),
                ('w_voice_uk', models.CharField(blank=True, max_length=32)),
                ('w_morph', models.JSONField()),
                ('w_tags', models.JSONField()),
                ('w_etyma', models.JSONField()),
                ('w_synonym', models.JSONField()),
                ('w_antonym', models.JSONField()),
                ('w_distinguish_id', models.JSONField()),
                ('w_grammar_id', models.JSONField()),
                ('w_origin', models.CharField(blank=True, max_length=512)),
                ('w_shorthand', models.CharField(blank=True, max_length=512)),
                ('w_paraphrase', models.JSONField(blank=True, max_length=512)),
            ],
            options={
                'db_table': 'Word',
            },
        ),
        migrations.CreateModel(
            name='StudyWord',
            fields=[
                ('sw_id', models.AutoField(primary_key=True, serialize=False)),
                ('sw_collect', models.JSONField()),
                ('sw_familiarity', models.IntegerField()),
                ('sw_repeats', models.IntegerField()),
                ('sw_learn_record', models.JSONField()),
                ('sw_inplan', models.BooleanField()),
                ('sw_comments', models.TextField()),
                ('sw_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.user')),
                ('sw_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.word')),
            ],
            options={
                'db_table': 'StudyWord',
            },
        ),
        migrations.CreateModel(
            name='StudySentence',
            fields=[
                ('ss_id', models.AutoField(primary_key=True, serialize=False)),
                ('ss_collect', models.JSONField()),
                ('ss_familiarity', models.IntegerField()),
                ('ss_repeats', models.IntegerField()),
                ('ss_learn_record', models.JSONField()),
                ('ss_inplan', models.BooleanField()),
                ('ss_new_words', models.JSONField()),
                ('ss_next_sentences', models.JSONField()),
                ('ss_comments', models.TextField()),
                ('ss_sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.sentence')),
                ('ss_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.user')),
            ],
            options={
                'db_table': 'StudySentence',
            },
        ),
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('sp_id', models.AutoField(primary_key=True, serialize=False)),
                ('sp_once_words', models.IntegerField()),
                ('sp_once_sentences', models.IntegerField()),
                ('sp_once_grammers', models.IntegerField()),
                ('sp_other_settings', models.JSONField()),
                ('sp_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.user')),
            ],
            options={
                'db_table': 'StudyPlan',
            },
        ),
        migrations.CreateModel(
            name='StudyGrammer',
            fields=[
                ('sg_id', models.AutoField(primary_key=True, serialize=False)),
                ('sg_familiarity', models.IntegerField()),
                ('sg_repeats', models.IntegerField()),
                ('sg_learn_record', models.JSONField()),
                ('sg_inplan', models.BooleanField()),
                ('sg_comments', models.TextField()),
                ('sg_grammer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.grammar')),
                ('sg_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.user')),
            ],
            options={
                'db_table': 'StudyGrammer',
            },
        ),
    ]
