# Generated by Django 3.1.1 on 2021-02-02 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distinguish',
            fields=[
                ('d_id', models.AutoField(primary_key=True, serialize=False)),
                ('d_words', models.JSONField()),
                ('d_content', models.TextField()),
                ('d_image', models.ImageField(upload_to='')),
                ('d_vedio', models.FilePathField(max_length=128)),
            ],
            options={
                'db_table': 'distinguish',
            },
        ),
        migrations.CreateModel(
            name='Etyma',
            fields=[
                ('e_name', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('e_meaning', models.TextField(blank=True, max_length=512)),
                ('e_type', models.IntegerField()),
                ('e_image', models.ImageField(upload_to='')),
                ('e_vedio', models.FilePathField(max_length=128)),
            ],
            options={
                'db_table': 'etyma',
            },
        ),
        migrations.CreateModel(
            name='Grammar',
            fields=[
                ('g_id', models.AutoField(primary_key=True, serialize=False)),
                ('g_type', models.JSONField()),
                ('g_tags', models.JSONField()),
                ('g_content', models.TextField(blank=True)),
                ('g_image', models.ImageField(upload_to='')),
                ('g_vedio', models.FilePathField(max_length=128)),
            ],
            options={
                'db_table': 'grammar',
            },
        ),
        migrations.CreateModel(
            name='Pronunciation',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=16)),
                ('p_content', models.TextField(blank=True)),
                ('s_example', models.JSONField()),
                ('p_image', models.ImageField(upload_to='')),
                ('s_redio', models.FilePathField()),
                ('p_vedio', models.FilePathField(max_length=128)),
            ],
            options={
                'db_table': 'pronunciation',
            },
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('s_en', models.CharField(max_length=512)),
                ('s_ch', models.CharField(max_length=512)),
                ('s_type', models.IntegerField(default=0)),
                ('s_tags', models.JSONField()),
                ('s_tense', models.JSONField()),
                ('s_form', models.JSONField()),
                ('s_synonym', models.JSONField()),
                ('s_antonym', models.JSONField()),
            ],
            options={
                'db_table': 'sentence',
            },
        ),
        migrations.CreateModel(
            name='Soundmark',
            fields=[
                ('s_name', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('s_type', models.JSONField()),
                ('s_content', models.CharField(blank=True, max_length=128)),
                ('s_example', models.JSONField()),
                ('s_image', models.ImageField(upload_to='')),
                ('s_redio', models.FilePathField()),
                ('s_vedio', models.FilePathField(max_length=128)),
            ],
            options={
                'db_table': 'soundmark',
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('w_name', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('w_voice_us', models.CharField(blank=True, max_length=32)),
                ('w_voice_uk', models.CharField(blank=True, max_length=32)),
                ('w_morph', models.JSONField()),
                ('w_tags', models.JSONField()),
                ('w_etyma', models.JSONField()),
                ('w_synonym', models.JSONField()),
                ('w_antonym', models.JSONField()),
                ('w_origin', models.CharField(blank=True, max_length=512)),
                ('w_shorthand', models.CharField(blank=True, max_length=256)),
                ('w_partofspeech', models.JSONField(blank=True, max_length=256)),
                ('w_sentence_pattern', models.JSONField(blank=True, max_length=256)),
                ('w_word_collocation', models.JSONField(blank=True, max_length=256)),
                ('w_image', models.ImageField(upload_to='')),
                ('w_vedio', models.FilePathField(max_length=128)),
            ],
            options={
                'db_table': 'word',
            },
        ),
        migrations.CreateModel(
            name='WordToSentence',
            fields=[
                ('wtg_id', models.AutoField(primary_key=True, serialize=False)),
                ('wtg_info', models.CharField(max_length=32)),
                ('wtg_sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.sentence')),
                ('wtg_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.word')),
            ],
            options={
                'db_table': 'word_to_sentence',
            },
        ),
        migrations.CreateModel(
            name='WordToGrammer',
            fields=[
                ('wtg_id', models.AutoField(primary_key=True, serialize=False)),
                ('wtg_grammer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.grammar')),
                ('wtg_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.word')),
            ],
            options={
                'db_table': 'word_to_grammer',
            },
        ),
        migrations.CreateModel(
            name='WordToDistinguish',
            fields=[
                ('wtd_id', models.AutoField(primary_key=True, serialize=False)),
                ('wtd_distinguish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.distinguish')),
                ('wtd_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.word')),
            ],
            options={
                'db_table': 'word_to_distinguish',
            },
        ),
        migrations.CreateModel(
            name='SentenceToGrammer',
            fields=[
                ('wtg_id', models.AutoField(primary_key=True, serialize=False)),
                ('wtg_grammer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.grammar')),
                ('wtg_sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.sentence')),
            ],
            options={
                'db_table': 'sentence_to_grammer',
            },
        ),
    ]
