# Generated by Django 3.1.1 on 2021-03-11 08:34

from django.db import migrations, models
import django.db.models.deletion
import server.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EtymaTable',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('interpretation', models.TextField(max_length=512, null=True)),
                ('type', models.IntegerField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='etyma_images/', verbose_name='图片讲解')),
                ('vedio', models.FileField(blank=True, null=True, upload_to='etyma_videos/', verbose_name='视频内容')),
            ],
        ),
        migrations.CreateModel(
            name='GrammarTagTable',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='GrammarTypeTable',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ParaphraseTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('interpret', models.CharField(max_length=128)),
                ('partOfSpeech', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='PronunciationTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16, null=True)),
                ('content', models.TextField(null=True)),
                ('example', server.models.JSONFieldUtf8(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pronunciation_images/', verbose_name='图片讲解')),
                ('vedio', models.FileField(blank=True, null=True, upload_to='pronunciation_vedios/', verbose_name='视频讲解')),
            ],
        ),
        migrations.CreateModel(
            name='SentenceTagTable',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SoundmarkTable',
            fields=[
                ('name', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('category', server.models.JSONFieldUtf8(null=True)),
                ('content', models.CharField(max_length=128, null=True)),
                ('example', server.models.JSONFieldUtf8(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='soundmark_images/', verbose_name='图片讲解')),
                ('vedio', models.FileField(blank=True, null=True, upload_to='soundmark_vedios/', verbose_name='视频讲解')),
            ],
        ),
        migrations.CreateModel(
            name='WordTagTable',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='WordTable',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('voiceUs', models.CharField(max_length=32, null=True)),
                ('voiceUk', models.CharField(max_length=32, null=True)),
                ('morph', server.models.JSONFieldUtf8(null=True)),
                ('tag', server.models.JSONFieldUtf8(null=True)),
                ('etyma', server.models.JSONFieldUtf8(null=True)),
                ('origin', models.CharField(max_length=512, null=True)),
                ('shorthand', models.CharField(max_length=256, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='word_images/', verbose_name='图片讲解')),
                ('vedio', models.FileField(blank=True, null=True, upload_to='word_videos/', verbose_name='视频讲解')),
                ('antonym', models.ManyToManyField(blank=True, related_name='_wordtable_antonym_+', to='dictionary.WordTable')),
                ('synonym', models.ManyToManyField(blank=True, related_name='_wordtable_synonym_+', to='dictionary.WordTable')),
            ],
        ),
        migrations.CreateModel(
            name='SentenceTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('en', models.CharField(max_length=512)),
                ('cn', models.CharField(max_length=512, null=True)),
                ('type', models.IntegerField(default=0)),
                ('tag', server.models.JSONFieldUtf8(null=True)),
                ('tense', server.models.JSONFieldUtf8(null=True)),
                ('pattern', server.models.JSONFieldUtf8(null=True)),
                ('antonym', models.ManyToManyField(blank=True, related_name='_sentencetable_antonym_+', to='dictionary.SentenceTable')),
                ('paraphrase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exampleSentences', to='dictionary.paraphrasetable')),
                ('synonym', models.ManyToManyField(blank=True, related_name='_sentencetable_synonym_+', to='dictionary.SentenceTable')),
            ],
        ),
        migrations.CreateModel(
            name='SentencePatternsTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=64)),
                ('foreignWord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.wordtable')),
            ],
        ),
        migrations.AddField(
            model_name='paraphrasetable',
            name='sentencePatternsForeign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentencePatternsParaphrase', to='dictionary.sentencepatternstable'),
        ),
        migrations.AddField(
            model_name='paraphrasetable',
            name='wordForeign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wordParaphrase', to='dictionary.wordtable'),
        ),
        migrations.CreateModel(
            name='GrammarTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', server.models.JSONFieldUtf8(null=True)),
                ('tag', server.models.JSONFieldUtf8(null=True)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='grammar_images/', verbose_name='图片讲解')),
                ('vedio', models.FileField(blank=True, null=True, upload_to='grammar_vedios/', verbose_name='视频讲解')),
                ('foreignSentence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sentenceGrammar', to='dictionary.sentencetable')),
                ('foreignWord', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wordGrammar', to='dictionary.wordtable')),
            ],
        ),
        migrations.CreateModel(
            name='DistinguishWordTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('words', server.models.JSONFieldUtf8()),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='distinguish_word_images/', verbose_name='图片讲解')),
                ('vedio', models.FileField(blank=True, null=True, upload_to='distinguish_word_videos/', verbose_name='视频讲解')),
                ('foreignWords', models.ManyToManyField(blank=True, to='dictionary.WordTable')),
            ],
        ),
    ]
