# Generated by Django 3.1.1 on 2021-02-03 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EtymaTable',
            fields=[
                ('e_name', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('e_meaning', models.TextField(max_length=512, null=True)),
                ('e_type', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PronunciationTable',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=16, null=True)),
                ('p_content', models.TextField(null=True)),
                ('s_example', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SentenceTable',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('s_en', models.CharField(max_length=512)),
                ('s_ch', models.CharField(max_length=512, null=True)),
                ('s_type', models.IntegerField(default=0)),
                ('s_tags', models.JSONField(null=True)),
                ('s_tense', models.JSONField(null=True)),
                ('s_form', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SoundmarkTable',
            fields=[
                ('s_name', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('s_type', models.JSONField(null=True)),
                ('s_content', models.CharField(max_length=128, null=True)),
                ('s_example', models.JSONField(null=True)),
                ('s_image', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='WordTable',
            fields=[
                ('w_name', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('w_voice_us', models.CharField(max_length=32, null=True)),
                ('w_voice_uk', models.CharField(max_length=32, null=True)),
                ('w_morph', models.JSONField(null=True)),
                ('w_tags', models.JSONField(null=True)),
                ('w_etyma', models.JSONField(null=True)),
                ('w_origin', models.CharField(max_length=512, null=True)),
                ('w_shorthand', models.CharField(max_length=256, null=True)),
                ('w_partofspeech', models.JSONField(max_length=256, null=True)),
                ('w_sentence_pattern', models.JSONField(max_length=256, null=True)),
                ('w_word_collocation', models.JSONField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WordToSentenceTable',
            fields=[
                ('wtg_id', models.AutoField(primary_key=True, serialize=False)),
                ('wtg_info', models.CharField(max_length=32)),
                ('wtg_sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.sentencetable')),
                ('wtg_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='dictionary.wordtable')),
            ],
        ),
        migrations.CreateModel(
            name='RelativeWordTable',
            fields=[
                ('r_id', models.AutoField(primary_key=True, serialize=False)),
                ('r_type', models.BooleanField(default=True)),
                ('r_word_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_word', to='dictionary.wordtable')),
                ('r_word_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.wordtable')),
            ],
        ),
        migrations.CreateModel(
            name='RelativeSentenceTable',
            fields=[
                ('r_id', models.AutoField(primary_key=True, serialize=False)),
                ('r_type', models.BooleanField(default=True)),
                ('r_sentence_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_sentence', to='dictionary.sentencetable')),
                ('r_sentence_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.sentencetable')),
            ],
        ),
        migrations.CreateModel(
            name='GrammarTable',
            fields=[
                ('g_id', models.AutoField(primary_key=True, serialize=False)),
                ('g_type', models.JSONField(null=True)),
                ('g_tags', models.JSONField(null=True)),
                ('g_content', models.TextField(blank=True)),
                ('g_sentence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grammar_sentence', to='dictionary.sentencetable')),
                ('g_word', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grammar_word', to='dictionary.wordtable')),
            ],
        ),
        migrations.CreateModel(
            name='DistinguishWordTable',
            fields=[
                ('d_id', models.AutoField(primary_key=True, serialize=False)),
                ('d_words', models.JSONField(null=True)),
                ('d_content', models.TextField(null=True)),
                ('d_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word', to='dictionary.wordtable')),
            ],
        ),
    ]
