# Generated by Django 3.1.1 on 2021-03-11 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SentencePatternsTable',
            new_name='SentencePatternTable',
        ),
        migrations.AlterModelOptions(
            name='etymatable',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='grammartable',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='sentencetable',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='wordtable',
            options={'ordering': ['name']},
        ),
    ]
