# Generated by Django 3.1.1 on 2021-02-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentencetable',
            name='s_form',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='sentencetable',
            name='s_tense',
            field=models.JSONField(null=True),
        ),
    ]
