# Generated by Django 3.1.1 on 2021-03-11 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_auto_20210311_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paraphrasetable',
            name='sentencePatternsForeign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sentencePatternsParaphrase', to='dictionary.sentencepatterntable'),
        ),
        migrations.AlterField(
            model_name='paraphrasetable',
            name='wordForeign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wordParaphrase', to='dictionary.wordtable'),
        ),
        migrations.AlterField(
            model_name='sentencepatterntable',
            name='foreignWord',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.wordtable'),
        ),
    ]
