# Generated by Django 3.1.1 on 2021-02-23 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_auto_20210222_1531'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PartOfSpeech',
            new_name='SentenceTagsTable',
        ),
    ]
