# Generated by Django 3.1.1 on 2021-03-11 10:02

from django.db import migrations, models
import django.db.models.deletion
import server.models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_auto_20210311_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distinguishwordtable',
            name='foreignWords',
            field=models.ManyToManyField(blank=True, related_name='distinguishSet', to='dictionary.WordTable'),
        ),
        migrations.AlterField(
            model_name='distinguishwordtable',
            name='words',
            field=server.models.JSONFieldUtf8(null=True),
        ),
        migrations.AlterField(
            model_name='grammartable',
            name='foreignSentence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grammarSet', to='dictionary.sentencetable'),
        ),
        migrations.AlterField(
            model_name='grammartable',
            name='foreignWord',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grammarSet', to='dictionary.wordtable'),
        ),
        migrations.AlterField(
            model_name='paraphrasetable',
            name='sentencePatternsForeign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paraphraseSet', to='dictionary.sentencepatterntable'),
        ),
        migrations.AlterField(
            model_name='paraphrasetable',
            name='wordForeign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paraphraseSet', to='dictionary.wordtable'),
        ),
        migrations.AlterField(
            model_name='sentencepatterntable',
            name='foreignWord',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sentencePatternSet', to='dictionary.wordtable'),
        ),
    ]
