# Generated by Django 3.1.1 on 2021-02-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_auto_20210223_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrammarTagTable',
            fields=[
                ('g_name', models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='GrammarTypeTable',
            fields=[
                ('g_name', models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
        ),
    ]
