# Generated by Django 3.1.1 on 2021-03-11 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0004_auto_20210311_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distinguishwordtable',
            old_name='foreignWords',
            new_name='wordsForeign',
        ),
        migrations.RenameField(
            model_name='sentencepatterntable',
            old_name='foreignWord',
            new_name='wordForeign',
        ),
    ]
