# Generated by Django 3.1.1 on 2021-03-11 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0005_auto_20210311_1804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grammartable',
            old_name='foreignSentence',
            new_name='sentenceForeign',
        ),
        migrations.RenameField(
            model_name='grammartable',
            old_name='foreignWord',
            new_name='wordForeign',
        ),
    ]
