# Generated by Django 3.1.1 on 2021-03-11 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0006_auto_20210311_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paraphrasetable',
            old_name='sentencePatternsForeign',
            new_name='sentencePatternForeign',
        ),
        migrations.AlterField(
            model_name='sentencetable',
            name='paraphrase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sentenceSet', to='dictionary.paraphrasetable'),
        ),
    ]
